{
 "title": "Network dashboard",
 "tags": [
  "Linux",
  "Network"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(node_network_info{job=\"$job\", instance=\"$node\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:500%;font-weight:bold;color:r#E2E8F0;>\"> NETWORK DASHBOARD </P>"
   }
  },
  {
   "title": "Resive bytes:",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])*8",
     "legendFormat": "Rx {{device}}"
    }
   ]
  },
  {
   "title": "Transmit bytes:",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])*8",
     "legendFormat": "Tx {{device}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Resived packets:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"$node\", job=\"$job\",device=~\"$device\"}[$__rate_interval])*8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit packets:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{instance=\"$node\", job=\"$job\",device=~\"$device\"}[$__rate_interval])*8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPOFOQueue{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Out-of-order Queued:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPRcvQDrop{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Receive Queue Drops:"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "tcp estab :"
    },
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{instance=\"$node\", job=\"$job\"}[1m])",
     "legendFormat": "act open :"
    },
    {
     "expr": "rate(node_netstat_Tcp_PassiveOpens{instance=\"$node\", job=\"$job\"}[1m])",
     "legendFormat": "tcp pass open :"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$node\", job=\"$job\"}[5m])",
     "legendFormat": "retransmit segments:"
    }
   ]
  },
  {
   "title": "TCP sockets:",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Allocated Sockets:"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "In-Use Sockets:"
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Orphaned Sockets:"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TIME_WAIT Sockets:"
    }
   ]
  },
  {
   "title": "Total TCP sockets:",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Total TCP sockets:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPTimeouts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "TCP Timeouts:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Receive Errors:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "SYN Retransmits:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Listen Overflows:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_OutRsts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "RST Sent:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Listen Drops:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Segment Retransmits:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$node\", job=\"$job\"}[1m])",
     "legendFormat": "syn retrans:"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "RSTs:"
    }
   ]
  },
  {
   "title": "Droped packets:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{instance=\"$node\", job=\"$job\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}}:"
    }
   ]
  },
  {
   "title": "Receive errors:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{instance=\"$node\", job=\"$job\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}}:"
    }
   ]
  },
  {
   "title": "Sockstat UDP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "UDPLite - In-Use Sockets:"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "UDP - In-Use Sockets:"
    }
   ]
  }
 ]
}