{
 "title": "first dashboard",
 "tags": [ "linux" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"},instance)"
    }
   },
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "grafana-clock-panel",
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 15, "x": 6, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:500%;font-weight:bold;color:#C8D200;>\"> RESOURCES DASHBOARD </P>"
   }
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "system",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "User",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "system"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 1m:"
    },
    {
     "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 5m:"
    },
    {
     "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 15m:"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100, 0)"
    }
   ]
  },
  {
   "title": "mem used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "mem used"
    }
   ]
  },
  {
   "title": "Cache + Buffer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Cache + Buffer"
    }
   ]
  },
  {
   "title": "Swap used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Mem Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Mem Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"} - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "Rx {{device}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "Tx {{device}} "
    }
   ]
  }
 ]
}